bar_joke_word = ["beers", "halls", "priorities",  "rivers", "procedures", "engineers", "problems", "industries",
                 "menus", "ads", "software", "dads", "weaknesses", "disasters", "fortunes", "governments", "desks",
                 "singers", "papers", "paper", "Powerpoint presentations", "passions", "memories", "TVs", "shirts",
                 "offices", "restaurants", "ears", "skills", "iPhone apps", "engines", "honey", "tennis", "baseball",
                 "colleges", "studio apartments", "upper management", "dating apps", "bottles of isopropyl alcohol",
                 "diaries", "ominous slack messagees", "bar graphs", "cameras", "conversations", "months",
                 "revolutions", "wood", "woods", "birch trees", "lava lamps", "bottle openers",
                 "public transportation", "nations", "instruction manuals", "the stock market", "stock markets",
                 "kings", "queens", "insects", "baskets", "salads", "society", "societies", "bluetooth speakers",
                 "dinner", "floppy disks", "oranges", "bananas", "baths", "hair dryers", "big data", "teeth",
                 "invisalign", "charity", "bread", "advil", "target", "Mark Ruffalo", "ballots", "zoos", "Monopoly",
                 "the army", "armies", "custard", "radar", "foreheads", "yeast", "eels", "hours", "icebergs", "trade",
                 "trades", "stereos", "stereo", "recessions", "patios", "resorts", "carbon footprints", "cafes",
                 "tubas", "ambulances", "orchestras", "produce", "fishermen", "goblins", "treasure", "fights", "jokes",
                 "improv", "cherries", "British National Grids", "grocery stores", "Buckingham Palace", "wine",
                 "Rubinoff", "the Eiffel Tower", "Boston Harbor", "science", "oil", "oils", "cities", "wealth",
                 "computers", "pizza", "sleep", "tents", "docks", "Centrum adult multigummies", "Fiji Waters",
                 "thrones", "soda", "churches", "alarm clocks", "almonds", "earthquakes", "regrets", "tests", "SATs",
                 "metals", "metal", "night", "nights", "calendars", "rice", "gold", "toothpaste", "toothbrushes",
                 "pens", "aloe vera", "cacti", "monitors", "Yeti Ramblers", "discord servers", "startup culture",
                 "yoyos", "neutron stars", "Super Smash Bros characters", "violins", "mice", "ice cubes",
                 "eldritch horrors", "unpaid interns", "fish", "improvisers", "moose", "clocks",]