pickup_lines_word = ["beer", "a hall", "a priority", "the internet", "a river", "a procedure", "engineering",
                     "a problem", "the industry", "a menu", "an ad", "software", "dad", "weakness", "a disaster",
                     "a fortune", "the government", "a desk", "a singer", "paper", "a Powerpoint presentation",
                     "passion", "memory", "TV", "a shirt", "an office", "a restaurant", "an ear", "a skill",
                     "an iPhone app", "an engine", "honey", "tennis", "baseball", "college", "a studio apartment",
                     "upper management", "dating app", "a bottle of isopropyl alcohol", "a diary",
                     "an ominous slack message", "a bar graph", "a camera", "a conversation", "a month", "a revolution",
                     "wood", "a birch tree", "a lava lamp", "a bottle opener", "public transportation", "a nation",
                     "an instruction manual", "the stock market", "a king", "a queen", "an insect", "a basket",
                     "a salad", "society", "a bluetooth speaker", "dinner", "brunch", "breakfast", "housing",
                     "a tongue", "an ear", "a nose", "an alien", "a UFO", "a floppy disk", "an orange", "a banana",
                     "a bath", "a hair dryer", "big data", "a tooth", "invisalign", "charity", "bread", "advil",
                     "target", "Mark Ruffalo", "a ballot", "a zoo", "Monopoly", "the army", "custard", "radar",
                     "a forehead", "yeast", "an eel", "an hour", "an iceberg", "a trade", "a stereo", "a recession",
                     "a patio", "a resort", "a carbon footprint", "a cafe", "a tuba", "an ambulance", "an orchestra",
                     "produce", "a fisherman", "a goblin", "a treasure", "a fight", "a joke", "improv", "a cherry",
                     "the British National Grid", "a grocery store", "Buckingham Palace", "wine", "Rubinoff",
                     "the Eiffel Tower", "Boston Harbor", "science", "oil", "a city", "wealth", "a computer", "pizza",
                     "sleep", "a tent", "a dock", "A Centrum adult multigummy", "Fiji Water", "a throne", "soda",
                     "a church", "an alarm clock", "an almond", "an earthquake", "regret", "a test", "an SAT", "metal",
                     "night", "a calendar", "rice", "gold", "toothpaste", "a toothbrush", "a pen", "aloe vera",
                     "a cactus", "a monitor", "a Yeti Rambler", "a discord server", "startup culture", "a bowling ball",
                     "Qdoba", "civil", "vengeful", "tangible", "magical", "little", "seemly", "judicious", "difficult",
                     "guilty", "healthy", "jagged", "wicked", "decisive", "tall", "psychedelic", "necessary", "mental",
                     "available", "lacking", "hungry", "knotty", "icky", "exlusive", "enchanted", "damp", "valuable",
                     "nostalgic", "habitual", "jealous", "charming", "faithful", "scattered", "kindly", "smart",
                     "meek", "war-hungry", "understood", "misunderstood", "lowly", "dusty", "victorious", "crowded",
                     "poor", "rich", "changeable", "slow", "speedy", "insidious", "nutritious", "keen", "high",
                     "elastic", "silent", "truthful", "synonymous", "lamentable", "fancy", "goofy", "impartial",
                     "productive", "industrious", "guiltless", "flaky", "acoustic", "tearful", "wrong", "threatening",
                     "towering", "infernal", "visible", "new", "well-to-do", "grumpy", "acceptable", "guarded",
                     "steady", "chilly", "materialistic", "dashing", "adamant",
                     "abstract", "cagey", "caustic", "The Middle Ages", "a computer mouse", "an ice cube"]